/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lab04;

import java.awt.Color;
import java.io.File;
import java.io.PrintWriter;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class Bai1 extends javax.swing.JFrame {

    /**
     * Creates new form Bai1
     */
    public Bai1() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnNew = new javax.swing.JButton();
        btnAbout = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        txtFpoly = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        edPage = new javax.swing.JTextPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        itmNew = new javax.swing.JMenuItem();
        itmOpen = new javax.swing.JMenuItem();
        itmSave = new javax.swing.JMenuItem();
        mnuColor = new javax.swing.JMenu();
        itmRed = new javax.swing.JMenuItem();
        itmGreen = new javax.swing.JMenuItem();
        itmBlue = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        itmTextColor = new javax.swing.JMenuItem();
        mnuSystem = new javax.swing.JMenu();
        itmAbout = new javax.swing.JMenuItem();
        itmExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/2.icon/icon/Text.png"))); // NOI18N
        btnNew.setToolTipText("");
        btnNew.setFocusable(false);
        btnNew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNew);

        btnAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/2.icon/icon/User.png"))); // NOI18N
        btnAbout.setFocusable(false);
        btnAbout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAbout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAbout);

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/2.icon/icon/Exit.png"))); // NOI18N
        btnExit.setFocusable(false);
        btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jToolBar1.add(btnExit);

        txtFpoly.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFpoly.setText("FPOLY - Java3");

        jScrollPane2.setViewportView(edPage);

        mnuFile.setText("File");

        itmNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/2.icon/icon/Text.png"))); // NOI18N
        itmNew.setText("New");
        itmNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmNewActionPerformed(evt);
            }
        });
        mnuFile.add(itmNew);

        itmOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/2.icon/icon/Open file.png"))); // NOI18N
        itmOpen.setText("Open");
        itmOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmOpenActionPerformed(evt);
            }
        });
        mnuFile.add(itmOpen);

        itmSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/2.icon/icon/Save as.png"))); // NOI18N
        itmSave.setText("Save");
        itmSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmSaveActionPerformed(evt);
            }
        });
        mnuFile.add(itmSave);

        jMenuBar1.add(mnuFile);

        mnuColor.setText("Color");

        itmRed.setText("Red");
        itmRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmRedActionPerformed(evt);
            }
        });
        mnuColor.add(itmRed);

        itmGreen.setText("Green");
        itmGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmGreenActionPerformed(evt);
            }
        });
        mnuColor.add(itmGreen);

        itmBlue.setText("Blue");
        itmBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmBlueActionPerformed(evt);
            }
        });
        mnuColor.add(itmBlue);
        mnuColor.add(jSeparator1);

        itmTextColor.setText("Text Color");
        itmTextColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmTextColorActionPerformed(evt);
            }
        });
        mnuColor.add(itmTextColor);

        jMenuBar1.add(mnuColor);

        mnuSystem.setText("System");

        itmAbout.setText("About us");
        itmAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAboutActionPerformed(evt);
            }
        });
        mnuSystem.add(itmAbout);

        itmExit.setText("Exit");
        itmExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmExitActionPerformed(evt);
            }
        });
        mnuSystem.add(itmExit);

        jMenuBar1.add(mnuSystem);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addComponent(txtFpoly))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFpoly, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itmAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAboutActionPerformed
        // TODO add your handling code here:
        String str = "Program demo menu";
        str += "\nAuthor: Phi Hùng";
        str += "\nLast Update: 20/07/2021";
        str +="\nEducation : Fpoly";
        JOptionPane.showMessageDialog(this, str);
    }//GEN-LAST:event_itmAboutActionPerformed

    private void itmNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmNewActionPerformed
        // TODO add your handling code here:
        edPage.setText("");
    }//GEN-LAST:event_itmNewActionPerformed

    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutActionPerformed
        // TODO add your handling code here:
        itmAboutActionPerformed(evt);
    }//GEN-LAST:event_btnAboutActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        itmNewActionPerformed(evt);
    }//GEN-LAST:event_btnNewActionPerformed

    private void itmExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_itmExitActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        itmExitActionPerformed(evt);
    }//GEN-LAST:event_btnExitActionPerformed

    private void itmTextColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmTextColorActionPerformed
        // TODO add your handling code here:
        Color c = JColorChooser.showDialog(null, "Chọn màu chữ", Color.white);
        txtFpoly.setForeground(c);
    }//GEN-LAST:event_itmTextColorActionPerformed

    private void itmRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmRedActionPerformed
        // TODO add your handling code here:
        txtFpoly.setBackground(Color.red);
    }//GEN-LAST:event_itmRedActionPerformed

    private void itmGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmGreenActionPerformed
        // TODO add your handling code here:
         txtFpoly.setBackground(Color.green);
    }//GEN-LAST:event_itmGreenActionPerformed

    private void itmBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmBlueActionPerformed
        // TODO add your handling code here:
         txtFpoly.setBackground(Color.blue);
    }//GEN-LAST:event_itmBlueActionPerformed

    private void itmOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmOpenActionPerformed
        // TODO add your handling code here:
        JFileChooser fchooser = new JFileChooser();
        int result = fchooser.showOpenDialog(null);
        if(result == JFileChooser.APPROVE_OPTION){
            try {
                edPage.setPage("file:///" +fchooser.getSelectedFile().getPath());
            } catch (Exception e) {
            }
        
        
        }
    }//GEN-LAST:event_itmOpenActionPerformed

    private void itmSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmSaveActionPerformed
        // TODO add your handling code here:
         JFileChooser fchooser = new JFileChooser();
        int result = fchooser.showOpenDialog(null);
        if(result == JFileChooser.APPROVE_OPTION){
            File fname = fchooser.getSelectedFile();
            try {
                PrintWriter pw = new PrintWriter(fname);
                pw.println(edPage.getText());
                pw.close();
            } catch (Exception e) {
            }
        
        
        }
    }//GEN-LAST:event_itmSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bai1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbout;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnNew;
    private javax.swing.JTextPane edPage;
    private javax.swing.JMenuItem itmAbout;
    private javax.swing.JMenuItem itmBlue;
    private javax.swing.JMenuItem itmExit;
    private javax.swing.JMenuItem itmGreen;
    private javax.swing.JMenuItem itmNew;
    private javax.swing.JMenuItem itmOpen;
    private javax.swing.JMenuItem itmRed;
    private javax.swing.JMenuItem itmSave;
    private javax.swing.JMenuItem itmTextColor;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenu mnuColor;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenu mnuSystem;
    private javax.swing.JTextField txtFpoly;
    // End of variables declaration//GEN-END:variables
}
