/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class test extends javax.swing.JFrame {
    Connection cn;
    DefaultTableModel model_tbl;
    int index;
    /**
     * Creates new form test
     */
    public test() {
        initComponents();
        setLocationRelativeTo(null);
        try {
            cn = Connect.ketnoi("TestAss1");
            if(cn != null){
                JOptionPane.showMessageDialog(this, "Kết nối thành công");
            } else {
                JOptionPane.showMessageDialog(this, "Kết nối thất bại");
            }
        } catch (Exception ex) {
            Logger.getLogger(test.class.getName()).log(Level.SEVERE, null, ex);
        }
        cboMonHoc.removeAllItems();
        cboMonHoc.addItem("COM1012");
        cboMonHoc.addItem("COM1022");
        cboMonHoc.addItem("COM2032");
        cboMonHoc.addItem("WEB1012");
        cboMonHoc.addItem("MUL1013");
        cboMonHoc.addItem("ENT1112");
        cboMonHoc.addItem("ENT1122");
        cboMonHoc.addItem("ENT2122");
        cboMonHoc.addItem("ENT2222");

        model_tbl = (DefaultTableModel) tblMonHoc.getModel();
        model_tbl.setColumnCount(0);
        model_tbl.addColumn("Mã SV");
        model_tbl.addColumn("Họ Tên");
        model_tbl.addColumn("Điểm");
        FillTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cboMonHoc = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMonHoc = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtMaSinhVien = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        txtDiem = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Môn học");

        cboMonHoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboMonHoc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboMonHocItemStateChanged(evt);
            }
        });
        cboMonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMonHocActionPerformed(evt);
            }
        });

        tblMonHoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMonHoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMonHocMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMonHoc);

        jLabel2.setText("Mã Sinh Viên");

        jLabel3.setText("Họ Tên");

        jLabel4.setText("Điểm");

        txtHoTen.setEditable(false);

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel1)
                        .addGap(40, 40, 40)
                        .addComponent(cboMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMaSinhVien)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                    .addComponent(txtDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "INSERT INTO DIEM VALUES (?,?,?)";
            PreparedStatement ptm = cn.prepareStatement(sql);
            ptm.setString(1, txtMaSinhVien.getText());
            ptm.setString(2, cboMonHoc.getSelectedItem()+"");
            ptm.setDouble(3, Double.parseDouble(txtDiem.getText()));
            check();
            ptm.executeUpdate();
            JOptionPane.showMessageDialog(this, "Thêm thành công");
            FillTable();
            ptm.close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here
        try {
            String sql = "UPDATE dbo.DIEM SET diem = ?\n" +
                            "WHERE Masv = ?";
            PreparedStatement ptm = cn.prepareStatement(sql);
            ptm.setDouble(1, Double.parseDouble(txtDiem.getText()));
            ptm.setString(2, txtMaSinhVien.getText());
            ptm.executeUpdate();
            JOptionPane.showMessageDialog(this, "Sửa thành công");
            FillTable();
            ptm.close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "DELETE FROM dbo.DIEM WHERE Masv = ? AND MaMH = ?";
            PreparedStatement ptm = cn.prepareStatement(sql);
            ptm.setString(1, txtMaSinhVien.getText());
            ptm.setString(2, cboMonHoc.getSelectedItem()+"");
            ptm.executeUpdate();
            JOptionPane.showMessageDialog(this, "Xóa thành công");
            FillTable();
            ptm.close();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void cboMonHocItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboMonHocItemStateChanged
        // TODO add your handling code here:
        try {
            String sql = "SELECT A.MaSV, A.HoTenSV, B.diem\n" +
                            "FROM dbo.SINHVIEN A JOIN dbo.DIEM B ON B.Masv = A.MaSV\n" +
                            "WHERE B.MaMH = ?";
            PreparedStatement ptm = cn.prepareStatement(sql);
            ptm.setString(1, cboMonHoc.getSelectedItem()+"");
            ResultSet rs = ptm.executeQuery();
            while(rs.next()){
                model_tbl.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3)});
                txtMaSinhVien.setText(tblMonHoc.getValueAt(0, 0).toString());
                txtHoTen.setText(tblMonHoc.getValueAt(0, 1).toString());
                txtDiem.setText(tblMonHoc.getValueAt(0, 2).toString());
            }
            FillTable();
            rs.close();
            ptm.close();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cboMonHocItemStateChanged

    private void tblMonHocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMonHocMouseClicked
        // TODO add your handling code here:
        index = tblMonHoc.getSelectedRow();
        showDetail(index);
    }//GEN-LAST:event_tblMonHocMouseClicked

    private void cboMonHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMonHocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboMonHocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new test().setVisible(true);
            }
        });
    }
    boolean check = true;
    boolean run = true;

    void check() {
        String sql = "SELECT MaSV FROM dbo.SINHVIEN ";
        check = true;
        run = true;
        try {
            PreparedStatement ptm = cn.prepareStatement(sql);
            ResultSet rs = ptm.executeQuery();
            while (rs.next()) {
                if (rs.getString(1).equalsIgnoreCase(txtMaSinhVien.getText())) {
                    check = false;
                    break;
                }
            }
            if (check) {
                JOptionPane.showMessageDialog(this, "Mã sinh viên không tồn tại");
                run = false;
            }
        } catch (SQLException ex) {
            Logger.getLogger(test.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (int i = 0; i < tblMonHoc.getRowCount(); i++) {
            if (txtMaSinhVien.getText().equalsIgnoreCase(tblMonHoc.getValueAt(i, 0) + "")) {
                JOptionPane.showMessageDialog(this, "Mã sinh viên đã tồn tại trong bảng");
                run = false;
            }
        }
    }
    
    void FillTable() {
        model_tbl.setRowCount(0);
        String sql = "SELECT A.MaSV, A.HoTenSV, B.diem\n" +
                        "FROM dbo.SINHVIEN A JOIN dbo.DIEM B ON B.Masv = A.MaSV\n" +
                        "WHERE B.MaMH = ?";
        try {
            PreparedStatement pstm = cn.prepareStatement(sql);
            pstm.setString(1, cboMonHoc.getSelectedItem() + "");
            ResultSet rs = pstm.executeQuery();
            while (rs.next()) {
                model_tbl.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getDouble(3)});
            }
        } catch (SQLException ex) {
            Logger.getLogger(test.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (tblMonHoc.getRowCount() > 0) {

            tblMonHoc.setRowSelectionInterval(0, 0);
            showDetail(0);
        } else {
            txtDiem.setText("");
            txtHoTen.setText("");
            txtMaSinhVien.setText("");
        }
    }
    
    void showDetail(int index){
        index = tblMonHoc.getSelectedRow();
        txtMaSinhVien.setText(tblMonHoc.getValueAt(index, 0).toString());
        cboMonHoc.setSelectedItem(tblMonHoc.getValueAt(index, 1).toString());
        
        txtDiem.setText(tblMonHoc.getValueAt(index, 2).toString());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cboMonHoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMonHoc;
    private javax.swing.JTextField txtDiem;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMaSinhVien;
    // End of variables declaration//GEN-END:variables
}
