/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QLSACH;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class Form extends javax.swing.JFrame {

    private Connection cn;
    DefaultTableModel model;

    /**
     * Creates new form Form
     */
    public Form() {
        initComponents();
        cn = Connect.ketnoi("QLSach");
        this.setLocationRelativeTo(null);
        model = (DefaultTableModel) tblShow.getModel();
        fillCBO();
        fillTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblShow = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cboTheLoai = new javax.swing.JComboBox<>();
        lblTenTheLoai = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnNew = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtMa = new javax.swing.JTextField();
        txtTen = new javax.swing.JTextField();
        txtNXB = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        txtGiaTien = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblShow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã sách", "Tên Sách", "Mã TL", "NXB", "Số Lượng", "Giá Tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblShow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblShowMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblShow);

        jLabel1.setText("Thể Loại");

        cboTheLoai.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboTheLoaiItemStateChanged(evt);
            }
        });

        lblTenTheLoai.setText("...........................");

        jLabel3.setText("Mã sách");

        jLabel4.setText("Tên Sách");

        jLabel5.setText("NXB");

        jLabel6.setText("Số Lượng");

        jLabel7.setText("Giá Tiền");

        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        txtMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(40, 40, 40)
                                .addComponent(cboTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(lblTenTheLoai))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMa)
                            .addComponent(txtTen, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .addComponent(txtNXB)
                            .addComponent(txtSoLuong)
                            .addComponent(txtGiaTien, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTenTheLoai))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(btnNew)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtNXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSave))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnDelete)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtGiaTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaActionPerformed

    private void tblShowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblShowMouseClicked
        // TODO add your handling code here:
        Display(tblShow.getSelectedRow());
    }//GEN-LAST:event_tblShowMouseClicked

    private void cboTheLoaiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboTheLoaiItemStateChanged
        // TODO add your handling code here:
        try {
//            String sql = "select Masach,TenSach,SACH.MaTheLoai,NXB,SoLuong,Giatien from SACH join THELOAI on "
//                    + "SACH.MaTheLoai = THELOAI.MaTheLoai where THELOAI.MaTheLoai = '" + cboTheLoai.getSelectedItem().toString().trim() + "'";
//            Statement st = cn.createStatement();
//            ResultSet rs = st.executeQuery(sql);
//            while (rs.next()) {
//                model.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6)});
//                txtMa.setText(tblShow.getValueAt(0, 0).toString());
//                txtTen.setText(tblShow.getValueAt(0, 1).toString());
//                txtNXB.setText(tblShow.getValueAt(0, 3).toString());
//                txtSoLuong.setText(tblShow.getValueAt(0, 4).toString());
//                txtGiaTien.setText(tblShow.getValueAt(0, 5).toString());
//
//            }

            String sql2 = "select TenTheLoai from THELOAI where MaTheLoai='" + cboTheLoai.getSelectedItem().toString() + "'";
            Statement st = cn.createStatement();
            ResultSet rs2 = st.executeQuery(sql2);
            while (rs2.next()) {
                lblTenTheLoai.setText(rs2.getString(1));
            }
            fillTable();
            if (tblShow.getRowCount() > 0) {
                tblShow.setRowSelectionInterval(0, 0);
                Display(0);
            } else {
                txtMa.setText("");
                txtTen.setText("");
                txtNXB.setText("");
                txtSoLuong.setText("");
                txtGiaTien.setText("");
                tblShow.clearSelection();
            }
        } catch (Exception e) {
            e.printStackTrace();
            
        }
    }//GEN-LAST:event_cboTheLoaiItemStateChanged

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        txtMa.setText("");
        txtTen.setText("");
        txtNXB.setText("");
        txtSoLuong.setText("");
        txtGiaTien.setText("");
        tblShow.clearSelection();
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        try {
            try {
                if (txtMa.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "Mã không được bỏ trống");
                    return;
                }
                String sql = "select Masach from SACH";
                Statement st = cn.createStatement();
                ResultSet rs = st.executeQuery(sql);
                while (rs.next()) {
                    if (txtMa.getText().equals(rs.getString(1))) {
                        JOptionPane.showMessageDialog(this, "Mã đã tồn tại");
                        return;
                    }

                }
            } catch (Exception e) {
                e.printStackTrace();
            }
            try {
                if (txtTen.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "Tên không được bỏ trống");
                    return;
                }
            } catch (Exception e) {
            }
            try {
                if (txtNXB.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "NXB không được bỏ trống");
                    return;
                }
            } catch (Exception e) {
            }

            try {
                if (txtSoLuong.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "Số lượng không được bỏ trống");
                    return;
                } else if (Integer.parseInt(txtSoLuong.getText()) <= 0) {
                    JOptionPane.showMessageDialog(this, "Số lượng phải lớn hơn 0");
                    return;
                }
            } catch (Exception e) {
                  JOptionPane.showMessageDialog(this, "Số lượng phải là số");
                    return;
            }
            try {
                
                if (txtGiaTien.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "Giá tiền không được bỏ trống");
                    return;
                }
                if (Double.parseDouble(txtGiaTien.getText()) <= 0) {
                    JOptionPane.showMessageDialog(this, "Giá tiền phải lơn hơn 0");
                    return;
                }
            } catch (Exception e) {
                  JOptionPane.showMessageDialog(this, "Giá tiền phải là số");
                    return;
            }

            String sql = "insert into SACH(Masach,TenSach,MaTheLoai,NXB,SoLuong,Giatien) values(?,?,?,?,?,?)";
            PreparedStatement ps = cn.prepareStatement(sql);
            ps.setString(1, txtMa.getText());
            ps.setString(2, txtTen.getText());
            ps.setString(3, cboTheLoai.getSelectedItem().toString());
            ps.setString(4, txtNXB.getText());
            ps.setString(5, txtSoLuong.getText());
            ps.setString(6, txtGiaTien.getText());
            ps.executeUpdate();

            JOptionPane.showMessageDialog(this, "thêm thành công");
            ps.close();
            fillTable();
            
        } catch (Exception e) {
            e.printStackTrace();

        }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "Delete from SACH where Masach = '"+ txtMa.getText()+"'";
        Statement st = cn.createStatement();
        st.executeUpdate(sql);
        JOptionPane.showMessageDialog(this, "Xoá thành công");
        fillTable();
       
            if (tblShow.getRowCount() > 0) {
                tblShow.setRowSelectionInterval(0, 0);
                Display(0);
            } else {
                txtMa.setText("");
                txtTen.setText("");
                txtNXB.setText("");
                txtSoLuong.setText("");
                txtGiaTien.setText("");
                tblShow.clearSelection();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_btnDeleteActionPerformed
    private void fillCBO() {
        try {
            String sql = "select MaTheLoai from THELOAI";
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                cboTheLoai.addItem(rs.getString(1));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void fillTable() {

        try {
            model.setRowCount(0);
            String sql = "select Masach,TenSach,SACH.MaTheLoai,NXB,SoLuong,Giatien from SACH join THELOAI on "
                    + "SACH.MaTheLoai = THELOAI.MaTheLoai where THELOAI.MaTheLoai = '" + cboTheLoai.getSelectedItem().toString().trim() + "'";
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6)});
            }
        } catch (Exception e) {
            e.printStackTrace();
            
        }

    }

    private void Display(int index) {
        index = tblShow.getSelectedRow();
        txtMa.setText(tblShow.getValueAt(index, 0).toString());
        txtTen.setText(tblShow.getValueAt(index, 1).toString());
        txtNXB.setText(tblShow.getValueAt(index, 3).toString());
        txtSoLuong.setText(tblShow.getValueAt(index, 4).toString());
        txtGiaTien.setText(tblShow.getValueAt(index, 5).toString());

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cboTheLoai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTenTheLoai;
    private javax.swing.JTable tblShow;
    private javax.swing.JTextField txtGiaTien;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtNXB;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables
}
